INSERT INTO CURRENCY_EXCHANGE(ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO) VALUES (1000, 10.5, '', 'USD', 'MAD')
INSERT INTO CURRENCY_EXCHANGE(ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO) VALUES (1001, 11.5, '', 'EUR', 'MAD')
INSERT INTO CURRENCY_EXCHANGE(ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO) VALUES (1002, 1.5, '', 'USD', 'EUR')